export const ACCOUNT_DATA = [
  {
    email: "admin@gmail.com",
    password: "admin",
    response: {
      datasDocumentId: "1234567890",
      datasId: "1",
      email: "admin@gmail.com",
      id: 1,
      image: "image url",
      name: "Admin",
      phoneNumber: "1234567890",
      role: "admin",
      status: "authenticated",
      token: "1234567890",
      username: "admin",
    },
    username: "admin",
  },
  {
    email: "user@gmail.com",
    password: "user",
    response: {
      datasDocumentId: "1234567890",
      datasId: "2",
      email: "user@gmail.com",
      id: 2,
      image: "image url",
      name: "User",
      phoneNumber: "1234567890",
      role: "user",
      status: "authenticated",
      token: "1234567890",
      username: "user",
    },
    username: "user",
  },
];

export const EXAMPLE_PACKAGES_DATA = [
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
    ],
    id: 1,
    price: "5000000",
    title: "PHOTOGRAPHY BASIC",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
    ],
    id: 2,
    price: "7000000",
    title: "PHOTOGRAPHY STANDARD",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
      { id: 7, text: "Framed Prints" },
    ],
    id: 3,
    price: "10000000",
    title: "PHOTOGRAPHY PREMIUM",
  },
  {
    description: [
      { id: 1, text: "Unlimited Photos" },
      { id: 2, text: "High-Resolution Images" },
      { id: 3, text: "Photo Editing" },
      { id: 4, text: "Online Gallery" },
      { id: 5, text: "Prints Available" },
      { id: 6, text: "Photo Album" },
      { id: 7, text: "Framed Prints" },
      { id: 8, text: "Custom Photo Book" },
    ],
    id: 4,
    price: "15000000",
    title: "PHOTOGRAPHY ULTIMATE",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
    ],
    id: 5,
    price: "8000000",
    title: "VIDEOGRAPHY BASIC",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
    ],
    id: 6,
    price: "12000000",
    title: "VIDEOGRAPHY STANDARD",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
      { id: 7, text: "Custom USB Drive" },
    ],
    id: 7,
    price: "18000000",
    title: "VIDEOGRAPHY PREMIUM",
  },
  {
    description: [
      { id: 1, text: "Full HD Video" },
      { id: 2, text: "Video Editing" },
      { id: 3, text: "Highlight Reel" },
      { id: 4, text: "Online Delivery" },
      { id: 5, text: "DVD Copy" },
      { id: 6, text: "Drone Footage" },
      { id: 7, text: "Custom USB Drive" },
      { id: 8, text: "Feature Film" },
    ],
    id: 8,
    price: "25000000",
    title: "VIDEOGRAPHY ULTIMATE",
  },
];
